echo Running the tests....
call mvn test -Dtest=GetTicketsTests
echo Generating the surefire report...
call mvn surefire-report:report
echo Opening the surefire report....
start target/site/surefire-report.html